version: '3'

networks:
  default:
    driver: bridge

services:

  app:
    build: ./apache
    environment:
      - APACHE_RUN_USER=www-data
    links:
      - db
    networks:
      - default
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}
  db:
    image: mysql:5.7
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jim
      MYSQL_DATABASE: jim
      MYSQL_USER: jim
      MYSQL_PASSWORD: jim
    volumes:
      - ./mysql/conf/:/etc/mysql/conf.d/
      - ${DB_PATH_HOST}:/var/lib/mysql/
    networks:
      - default
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - '6080:80'
      - '6043:443'
    environment:
      - PHPMYADMIN_ALLOW_NO_PASSWORD=false
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
    volumes:
      - pma_data:/bitnami
    networks:
      - default
  composer:
    image: composer:1.6
    networks:
      - default
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install

volumes:
  pma_data:
    driver: local